"""Static recompiler for WET.EXE: python3 -m tools.recomp --out DIR.

Writes C sources for every discovered guest function plus the tables the
runtime needs (function entry table, import table, image hash). The output is
generated build data; keep it under build/.
"""
import argparse
import csv
import json
import os
import re
import sys
import time
from pathlib import Path

from . import cfg, flags, lift, pe

ROOT = Path(__file__).resolve().parents[2]
DEFAULT_EXE = ROOT / 'original' / 'app' / 'WET.EXE'
FUNCTIONS_TSV = ROOT / 'analysis' / 'decompiled' / 'functions.tsv'
CONFIG = Path(__file__).resolve().parent / 'config.json'
RECONSTRUCTED = ROOT / 'src' / 'reconstructed'

HEADER = '/* Generated by tools/recomp from WET.EXE. Do not edit; regenerate instead. */\n'


def load_config():
    data = json.loads(CONFIG.read_text(encoding='utf-8'))
    as_int = lambda xs: {int(x, 16) for x in xs}
    return as_int(data.get('extra_entries', [])), as_int(data.get('blacklist', []))


def reconstructed_functions():
    """Entries replaced by hand-written C: RT_RECONSTRUCTED(0x...) markers."""
    found = {}
    for path in sorted(RECONSTRUCTED.glob('*.c')):
        for m in re.finditer(r'RT_RECONSTRUCTED\(\s*0x([0-9a-fA-F]+)\s*\)', path.read_text(encoding='utf-8')):
            found[int(m.group(1), 16)] = path.relative_to(ROOT).as_posix()
    return found


def check_profiles():
    """Argument profiles for tools/fncheck: RT_CHECK(0x..., "eax:ptr ...")."""
    found = {}
    for path in sorted(RECONSTRUCTED.glob('*.c')):
        text = path.read_text(encoding='utf-8')
        for m in re.finditer(r'RT_CHECK\(\s*0x([0-9a-fA-F]+)\s*,\s*"([^"]*)"\s*\)', text):
            found[int(m.group(1), 16)] = m.group(2)
    return found


def seeds_from_ghidra(path):
    seeds = set()
    if path.is_file():
        with path.open(encoding='utf-8') as stream:
            for row in csv.DictReader(stream, delimiter='\t'):
                seeds.add(int(row['entry'], 16))
    return seeds


def write_if_changed(path, text):
    path = Path(path)
    if path.exists() and path.read_text(encoding='utf-8') == text:
        return False
    tmp = path.with_suffix(path.suffix + '.tmp')
    tmp.write_text(text, encoding='utf-8')
    os.replace(tmp, path)
    return True


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument('--exe', default=str(DEFAULT_EXE))
    ap.add_argument('--out', required=True, help='output directory for generated C')
    ap.add_argument('--per-file', type=int, default=40, help='functions per C file')
    ap.add_argument('--only', help='comma separated function entries (debugging)')
    args = ap.parse_args(argv)

    t0 = time.time()
    img = pe.load(args.exe)
    extra, blacklist = load_config()
    seeds = {img.entry} | seeds_from_ghidra(FUNCTIONS_TSV) | extra
    prog = cfg.Program(img)
    prog.discover(seeds, blacklist=blacklist)
    live = flags.Liveness(prog).solve()

    host = {slot: imp.host_symbol for slot, imp in img.imports.items()}
    lifter = lift.Lifter(prog, live, host)
    out = Path(args.out)
    out.mkdir(parents=True, exist_ok=True)

    entries = sorted(prog.functions)
    if args.only:
        wanted = {int(x, 16) for x in args.only.split(',')}
        entries = [e for e in entries if e in wanted]

    decls = [HEADER, '#pragma once', '#include "rt_cpu.h"', '']
    decls += [f'uint32_t f_{e:08x}(Cpu *c);' for e in sorted(prog.functions)]
    host_syms = sorted({imp.host_symbol for imp in img.imports.values()})
    decls += [f'uint32_t {s}(Cpu *c);' for s in host_syms]
    write_if_changed(out / 'gen_decls.h', '\n'.join(decls) + '\n')

    # Hand-reconstructed functions replace the generated ones. The generated
    # version stays available as lifted_XXXXXXXX for comparison.
    replaced = reconstructed_functions()
    unknown = sorted(a for a in replaced if a not in prog.functions)
    if unknown:
        raise SystemExit('RT_RECONSTRUCTED for addresses that are not function entries: ' +
                         ', '.join(f'{a:#x}' for a in unknown))
    for a in replaced:
        if live.ret_live.get(a) or live.entry_live.get(a):
            print(f'warning: reconstructed {a:#x} must also produce/consume flags '
                  f'(entry {live.entry_live.get(a, 0):#x}, return {live.ret_live.get(a, 0):#x})',
                  file=sys.stderr)
    decls += [f'uint32_t lifted_{e:08x}(Cpu *c);' for e in sorted(replaced)]
    write_if_changed(out / 'gen_decls.h', '\n'.join(decls) + '\n')

    files = []
    for i in range(0, len(entries), args.per_file):
        chunk = entries[i:i + args.per_file]
        body = [HEADER, '#include "gen_decls.h"', '#include <math.h>', '']
        for e in chunk:
            text = lifter.function(prog.functions[e])
            if e in replaced:
                text = f'/* Replaced by {replaced[e]}; generated version kept for comparison. */\n' + \
                    text.replace(f'uint32_t f_{e:08x}(Cpu *c)', f'uint32_t lifted_{e:08x}(Cpu *c)', 1)
            body.append(text)
            body.append('')
        name = f'funcs_{i // args.per_file:03d}.c'
        write_if_changed(out / name, '\n'.join(body))
        files.append(name)

    table = [HEADER, '#include "gen_decls.h"', '#include "rt_tables.h"', '',
             f'const char g_image_sha256[] = "{img.sha256}";',
             f'const uint32_t g_image_base = 0x{img.base:08x}u;',
             f'const uint32_t g_image_size = 0x{img.size:08x}u;',
             f'const uint32_t g_image_entry = 0x{img.entry:08x}u;',
             f'const uint32_t g_stack_reserve = 0x{img.stack_reserve:08x}u;',
             '', 'const GuestEntry g_guest_entries[] = {']
    table += [f'    {{0x{e:08x}u, f_{e:08x}}},' for e in sorted(prog.functions)]
    table += ['};', f'const size_t g_guest_entry_count = {len(prog.functions)};', '',
              'const HostImport g_host_imports[] = {']
    for slot in sorted(img.imports):
        imp = img.imports[slot]
        table.append(f'    {{0x{slot:08x}u, "{imp.dll}", "{imp.name}", {imp.host_symbol}}},')
    table += ['};', f'const size_t g_host_import_count = {len(img.imports)};', '']
    write_if_changed(out / 'gen_tables.c', '\n'.join(table))

    stubs = [HEADER, '#include "gen_decls.h"', '',
             '/* Weak fallbacks: the runtime overrides every import it implements. */']
    for slot in sorted(img.imports):
        imp = img.imports[slot]
    for s in host_syms:
        stubs.append(f'RT_WEAK uint32_t {s}(Cpu *c) {{ return rt_unimplemented(c, "{s[2:]}"); }}')
    write_if_changed(out / 'gen_stubs.c', '\n'.join(stubs) + '\n')
    profiles = check_profiles()
    recon = [HEADER, '#include "gen_decls.h"', '#include "rt_tables.h"', '',
             '/* Reconstructed functions with their generated counterparts (tools/fncheck). */',
             'const ReconEntry g_reconstructed[] = {']
    for a in sorted(replaced):
        mask = live.ret_live.get(a, 0)
        recon.append(f'    {{0x{a:08x}u, f_{a:08x}, lifted_{a:08x}, 0x{mask:02x}u, '
                     f'{json.dumps(profiles.get(a, ""))}}},')
    recon += ['    {0, 0, 0, 0, 0}', '};', f'const size_t g_reconstructed_count = {len(replaced)};', '']
    write_if_changed(out / 'gen_reconstructed.c', '\n'.join(recon))
    files += ['gen_tables.c', 'gen_stubs.c', 'gen_reconstructed.c']

    report = {
        'image_sha256': img.sha256,
        'functions': len(prog.functions),
        'instructions_unique': len({a for f in prog.functions.values() for a in f.insns}),
        'instructions_lifted': sum(len(f.insns) for f in prog.functions.values()),
        'jump_tables': len(prog.table_vas),
        'unsupported': lifter.unsupported,
        'flag_warnings': sorted(set(live.warnings)),
        'notes': prog.notes,
        'reconstructed': {f'{a:#x}': p for a, p in sorted(replaced.items())},
        'unowned_code_pointers': [f'{r:#x}->{v:#x}' for r, v, k in prog.code_pointer_relocs()
                                  if k == 'text-unowned'],
        'files': files,
        'seconds': round(time.time() - t0, 1),
    }
    write_if_changed(out / 'report.json', json.dumps(report, indent=2) + '\n')
    write_if_changed(out / 'sources.txt', '\n'.join(files) + '\n')
    print(f"recomp: {report['functions']} functions, {report['instructions_unique']} instructions, "
          f"{len(lifter.unsupported)} unsupported kinds, {report['seconds']} s -> {out}")
    if lifter.unsupported:
        for k, v in sorted(lifter.unsupported.items()):
            print(f'  unsupported {k}: {v}', file=sys.stderr)
    return 0


if __name__ == '__main__':
    sys.exit(main())
